// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqo5B_weodFoknQMKQIncI49YkWY6HBXY',
    appId: '1:249560275022:web:0670c16896a4a459374b1f',
    messagingSenderId: '249560275022',
    projectId: 'lapor-book-4d4f3',
    authDomain: 'lapor-book-4d4f3.firebaseapp.com',
    storageBucket: 'lapor-book-4d4f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy_LtAjZz8Bpiiukkl1uMuEESyRgYBstw',
    appId: '1:249560275022:android:593cb161139ff236374b1f',
    messagingSenderId: '249560275022',
    projectId: 'lapor-book-4d4f3',
    storageBucket: 'lapor-book-4d4f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqZp2SFm_eyIgcK5nOg2xoiy8-poQWkBY',
    appId: '1:249560275022:ios:0df20d81b1985ddd374b1f',
    messagingSenderId: '249560275022',
    projectId: 'lapor-book-4d4f3',
    storageBucket: 'lapor-book-4d4f3.appspot.com',
    iosBundleId: 'com.example.laporBook',
  );
}
